# Generated by Django 3.0.8 on 2020-07-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200721_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified_mail',
            new_name='verified_email',
        ),
    ]
