# Generated by Django 3.0.8 on 2020-07-22 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200722_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Enter valid first number', regex='w*[a-z|A-Z]')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Enter valid last number', regex='w*[a-z|A-Z]')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid phone number', regex='^[9|8|7|6]\\d{9}')]),
        ),
    ]
