# Generated by Django 3.0.8 on 2020-07-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200724_1054'),
        ('account', '0007_auto_20200724_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(null=True, to='product.Product'),
        ),
    ]
