# Generated by Django 3.0.8 on 2020-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200724_1054'),
        ('account', '0009_auto_20200729_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
