# Generated by Django 3.0.8 on 2020-08-01 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200730_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('pincode', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='First name should not contain symbols, number or whitespace', regex='^\\w[a-z|A-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Last name should not contain symbols, number or whitespace', regex='^\\w[a-z|A-Z]+$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(limit_choices_to=5, to='account.Address'),
        ),
    ]
