# Generated by Django 3.0.8 on 2020-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200801_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, limit_choices_to=5, to='account.Address'),
        ),
    ]
