# Generated by Django 3.0.8 on 2020-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200724_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default='product/images/not_found.jpg', upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default='product/images/not_found.jpg', upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default='product/images/not_found.jpg', upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='product/images/not_found.jpg', upload_to='images/product'),
        ),
    ]
